# Visio Stencil Explorer Configuration

# Application Settings
app:
  title: "Visio Stencil Explorer"
  description: "A tool to catalog and search Visio stencil files"
  version: "1.0.0"
  debug: false
  log_level: "info"  # Options: debug, info, warning, error, critical

# User Preferences
user_preferences:
  # Default startup directory
  default_startup_directory: "./test_data"
  # Default search mode (true = FTS, false = Standard)
  default_search_mode: true
  # Default result limit
  default_result_limit: 1000
  # Show metadata columns by default
  show_metadata_columns: false

# Default Paths
paths:
  # Default stencil directory to scan
  stencil_directory: "./test_data"
  # Where to store the SQLite database
  database: "data/stencil_cache.db"
  # Where to store exported reports
  exports: "exports"

# Scanning Settings
scanner:
  # File extensions to scan
  extensions:
    - ".vss"
    - ".vssx"
    - ".vssm"
    - ".vst"
    - ".vstx"
  # Auto-refresh interval in hours (0 = disabled)
  auto_refresh_interval: 1
  # Maximum number of stencils to process in a batch
  batch_size: 100

# Temp File Cleaner Settings
temp_cleaner:
  # File patterns to look for
  patterns:
    - "~$$*.*vssx"
  # Default scan directory
  default_directory: "~/Documents"

# Stencil Health Settings
health:
  # Severity thresholds (number of issues to trigger severity)
  thresholds:
    low: 1
    medium: 5
    high: 10